# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy
    - scripts/completions.sh


builds:
  - main: main.go
    ldflags:
      - -s -w -X github.com/alphagov/govuk-cli/cmd.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64
      - amd64
    binary: govuk

archives:
  - formats: ["tar.gz"]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - completions/*

universal_binaries:
  - replace: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  draft: false
  use_existing_draft: true
  replace_existing_artifacts: true

homebrew_casks:
  - name: govuk-cli
    license: MIT
    homepage: "https://github.com/alphagov/govuk-cli"
    completions:
      bash: "completions/govuk-cli.bash"
      fish: "completions/govuk-cli.fish"
      zsh: "completions/govuk-cli.zsh"
    repository:
      owner: alphagov
      name: homebrew-gds
      token: "{{ .Env.GITHUB_PAT_HOMEBREW }}"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/govuk-cli"]
          end
